### ISSUE TITLE
tendrl_server.yml and tendrl_node.yml use root user for all operations

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/usmqe-setup#76]
The option to use a non root user with "become: True" should be allowed but perhaps commented out. This gives better security and logging via the system sudo facilities.

**Comment by mbukatov** [comment]
That boils down to the question how much our current qe playbooks should be reusable for production deployments. This is not the case right now, but we plan to discuss this among all qe team members next week (2 guys were not available this week).

My perception of this issue is:

* I don't think that using dedicated user and then switching to root via sudo is more secure compared to just using root account directly - as long as ssh server is configured to use public key auth only.

* On the one hand that logging via sudo may be interesting, but on the other hand, it would require additional setup (user configuration, sudo configuration, ssh key deployment on all cluster machines). The other problem could be that we would not be strictly following documentation - even when this is trivial case and it should work anyway, we should try to follow documentation exactly (almost blindly) as much as we can, because it would help us discover possible issues with suggested setup.

**Comment by japplewhite** [comment]
One primary use case here is vagrant. In that instance the sudoers setup is
[root@tendrl ~]# cat /etc/sudoers.d/vagrant
%vagrant ALL=(ALL) NOPASSWD: ALL
and there is not an option to use root.

**Comment by mkudlej** [comment]
@japplewhite I think that we should follow ceph-ansible here:

> Ansible must login to Ceph nodes as a user that has passwordless root privileges, because Ansible needs to install software and configuration files without prompting for passwords. 

So I think that it is on admin to set up password-less connection to root for all nodes. This should not be set in usmqe-setup playbooks.

**Comment by japplewhite** [comment]
@mbukatov @mkudlej I disagree with you both here. It is quite commonplace in ansible to use non root users for better security and logging. It makes no difference whether a playbook is run with root or with a sudo user setup in the fashion I mentioned above. The net result is that the command is run as super user 0 in either case.

**Comment by mbukatov** [comment]
Since we pushed the tendrl-ansible unification plan further, I guess we can close this one. @japplewhite: are you ok with this?

**Comment by japplewhite** [comment]
@mbukatov I have found a workaround for this issue that I think should be part of the documentation. If you call the playbook as follows:
`ansible-playbook -u vagrant -b site.yml`
it will automatically overload the user and attempt to use sudo with no change in the playbooks. So there is no need to change from root. We just need to document that as a workaround.
So yes we can close this.

**Comment by mbukatov** [comment]
Ok, I'm closing this here.

**Comment by japplewhite** [comment]
sure
